apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: YWRtaW4=      # admin required field for kubernetes.io/basic-auth
  mongo-password: dDBwLVNlY3JldA==  # t0p-Secret t0p-Secretrequired field for kubernetes.io/basic-auth